'use strict';
const fs=require('fs');const path=require('path');const engine=require('../../utils/fileLabEngine');
const CAT='🧰 FILE LAB / CONVERTERS';
function err(e){return`❌ *File Lab*\n${String(e?.message||e||'Erreur inconnue').slice(0,800)}`}
function opts(msg,from){return from?.endsWith('@g.us')?{quoted:msg}:undefined}
async function sendDoc(sock,msg,from,file,name,mime='application/octet-stream'){await sock.sendMessage(from,{document:fs.readFileSync(file),fileName:name||path.basename(file),mimetype:mime},opts(msg,from))}
const commands=[];
for(const [name,fmt,mime,desc] of [['tojpg','jpg','image/jpeg','Convertir une image en JPEG'],['topng','png','image/png','Convertir une image en PNG'],['towebp','webp','image/webp','Convertir une image en WebP'],['toavif','avif','image/avif','Convertir une image en AVIF']])commands.push({name,aliases:[],category:CAT,description:desc,usage:`.${name} [qualité]`,async execute(sock,msg,args,extra){let i,out;try{i=await engine.getInput(msg);out=await engine.imageConvert(i.file,fmt,{quality:args[0]});await sock.sendMessage(extra.from,{image:fs.readFileSync(out),caption:`🖼️ Conversion ${fmt.toUpperCase()} terminée.`},opts(msg,extra.from));}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,out);}}});
commands.push({name:'resize',aliases:['resizeimg'],category:CAT,description:'Redimensionner une image',usage:'.resize <largeur> [hauteur]',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.imageConvert(i.file,'jpg',{width:Number(args[0])||1080,height:Number(args[1])||null,quality:88});await sock.sendMessage(extra.from,{image:fs.readFileSync(o),caption:'📐 Image redimensionnée.'},opts(msg,extra.from));}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'rotateimg',aliases:['rotate'],category:CAT,description:'Tourner une image',usage:'.rotateimg <degrés>',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.imageConvert(i.file,'png',{rotate:Number(args[0])||90});await sock.sendMessage(extra.from,{image:fs.readFileSync(o),caption:'🔄 Rotation terminée.'},opts(msg,extra.from));}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'grayscale',aliases:['grayimg'],category:CAT,description:'Convertir une image en niveaux de gris',usage:'.grayscale',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.imageConvert(i.file,'jpg',{grayscale:true,quality:90});await sock.sendMessage(extra.from,{image:fs.readFileSync(o),caption:'◾ Niveaux de gris appliqués.'},opts(msg,extra.from));}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'compressimg',aliases:['imgcompress'],category:CAT,description:'Compresser une image',usage:'.compressimg [qualité 20-100]',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.imageConvert(i.file,'jpg',{quality:Number(args[0])||65});await sock.sendMessage(extra.from,{image:fs.readFileSync(o),caption:`🗜️ Image compressée — ${(fs.statSync(o).size/1048576).toFixed(2)} Mo.`},opts(msg,extra.from));}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
for(const [name,fmt,mime,desc] of [['tomp4','mp4','video/mp4','Convertir une vidéo en MP4'],['towebm','webm','video/webm','Convertir une vidéo en WebM'],['tomp3','mp3','audio/mpeg','Extraire/convertir en MP3'],['toogg','ogg','audio/ogg','Convertir en OGG'],['towav','wav','audio/wav','Convertir en WAV'],['togif','gif','image/gif','Créer un GIF court depuis une vidéo']])commands.push({name,aliases:[],category:CAT,description:desc,usage:`.${name}`,async execute(sock,msg,args,extra){let i,o;try{await extra.reply(`⚙️ Conversion ${fmt.toUpperCase()} en cours…`);i=await engine.getInput(msg);o=await engine.videoConvert(i.file,fmt);const data=fs.readFileSync(o);if(fmt==='mp3'||fmt==='ogg'||fmt==='wav')await sock.sendMessage(extra.from,{audio:data,mimetype:mime,fileName:`DIPPER.${fmt}`,ptt:false},opts(msg,extra.from));else if(fmt==='mp4'||fmt==='webm')await sock.sendMessage(extra.from,{video:data,mimetype:mime,fileName:`DIPPER.${fmt}`},opts(msg,extra.from));else await sendDoc(sock,msg,extra.from,o,`DIPPER.${fmt}`,mime);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'img2pdf',aliases:['image2pdf','topdf'],category:CAT,description:'Convertir l’image citée en PDF',usage:'.img2pdf',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.imagesToPdf([i.file]);await sendDoc(sock,msg,extra.from,o,'DIPPER-image.pdf','application/pdf');}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'pdf2img',aliases:['pdftopng'],category:CAT,description:'Rendre les pages d’un PDF en images',usage:'.pdf2img [pages max 1-10]',async execute(sock,msg,args,extra){let i,r;try{await extra.reply('📄 Rendu PDF en cours…');i=await engine.getInput(msg);r=await engine.pdfToImages(i.file,Math.max(1,Math.min(10,Number(args[0])||6)));for(let n=0;n<r.files.length;n++)await sock.sendMessage(extra.from,{image:fs.readFileSync(r.files[n]),caption:`📄 Page ${n+1}/${r.totalPages}`},opts(msg,extra.from));if(r.totalPages>r.files.length)await extra.reply(`ℹ️ ${r.totalPages-r.files.length} page(s) non envoyée(s). Relance avec une limite supérieure (max 10).`);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,r?.files);}}});
commands.push({name:'zip',aliases:['makezip'],category:CAT,description:'Créer une archive ZIP du fichier cité',usage:'.zip [nom]',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=engine.zipFiles([i.file],[i.name]);await sendDoc(sock,msg,extra.from,o,`${engine.safeName(args[0]||'DIPPER')}.zip`,'application/zip');}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'unzip',aliases:['extractzip'],category:CAT,description:'Extraire une archive ZIP',usage:'.unzip',async execute(sock,msg,args,extra){let i,files=[];try{i=await engine.getInput(msg);files=engine.unzip(i.file);if(!files.length)return extra.reply('ℹ️ Archive vide.');for(const f of files.slice(0,12))await sendDoc(sock,msg,extra.from,f,path.basename(f));if(files.length>12)await extra.reply(`ℹ️ ${files.length-12} fichier(s) supplémentaires non envoyés pour éviter le spam.`);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,files,files[0]&&path.dirname(files[0]));}}});
commands.push({name:'7z',aliases:['make7z'],category:CAT,description:'Créer une archive 7z du fichier cité',usage:'.7z',async execute(sock,msg,args,extra){let i,o;try{i=await engine.getInput(msg);o=await engine.seven(null,'add',[i.file]);await sendDoc(sock,msg,extra.from,o,'DIPPER.7z','application/x-7z-compressed');}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,o);}}});
commands.push({name:'un7z',aliases:['extract7z'],category:CAT,description:'Extraire une archive 7z',usage:'.un7z',async execute(sock,msg,args,extra){let i,files=[];try{i=await engine.getInput(msg);files=await engine.seven(i.file,'extract');for(const f of files.slice(0,12))await sendDoc(sock,msg,extra.from,f,path.basename(f));if(!files.length)await extra.reply('ℹ️ Archive vide.');}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,files,files[0]&&path.dirname(files[0]));}}});
commands.push({name:'unrar',aliases:['extractrar','rar'],category:CAT,description:'Extraire une archive RAR',usage:'.unrar',async execute(sock,msg,args,extra){let i,files=[];try{i=await engine.getInput(msg);files=await engine.unrar(i.file);for(const f of files.slice(0,12))await sendDoc(sock,msg,extra.from,f,path.basename(f));if(!files.length)await extra.reply('ℹ️ Archive RAR vide.');}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file,files,files[0]&&path.dirname(files[0]));}}});
commands.push({name:'archiveinfo',aliases:['zipinfo'],category:CAT,description:'Inspecter une archive ZIP',usage:'.archiveinfo',async execute(sock,msg,args,extra){let i;try{i=await engine.getInput(msg);const x=engine.archiveInfo(i.file);await extra.reply(`🗃️ *Archive ${x.type}*\nEntrées : ${x.count??'analyse détaillée non disponible'}\n\n${x.names.join('\n')||'—'}`);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file);}}});
commands.push({name:'filehash',aliases:['sha256','checksum'],category:CAT,description:'Calculer le SHA-256 d’un fichier',usage:'.filehash',async execute(sock,msg,args,extra){let i;try{i=await engine.getInput(msg);await extra.reply(`🔐 *SHA-256*\n${engine.hash(i.file,'sha256')}`);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file);}}});
commands.push({name:'md5',aliases:[],category:CAT,description:'Calculer le MD5 d’un fichier',usage:'.md5',async execute(sock,msg,args,extra){let i;try{i=await engine.getInput(msg);await extra.reply(`🔐 *MD5*\n${engine.hash(i.file,'md5')}`);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file);}}});
commands.push({name:'renamefile',aliases:['rename'],category:CAT,description:'Renvoyer un fichier avec un nouveau nom',usage:'.renamefile <nouveau nom>',async execute(sock,msg,args,extra){let i;try{i=await engine.getInput(msg);const n=engine.safeName(args.join(' ')||i.name);await sendDoc(sock,msg,extra.from,i.file,n,i.mime);}catch(e){await extra.reply(err(e));}finally{engine.cleanup(i?.file);}}});
module.exports=commands;
