'use strict';
const fs=require('fs');const axios=require('axios');const engine=require('../../utils/downloadEngine');const fileLab=require('../../utils/fileLabEngine');
const CAT='📥 DOWNLOAD / FILE TOOLS';
async function uploadPixeldrain(file,name){const safe=fileLab.safeName(name||'file.bin');const url=`https://pixeldrain.com/api/file/${encodeURIComponent(safe)}`;const stat=fs.statSync(file);const r=await axios.put(url,fs.createReadStream(file),{timeout:180000,maxBodyLength:Infinity,maxContentLength:Infinity,headers:{'Content-Type':'application/octet-stream','Content-Length':stat.size,'User-Agent':'THE_BIG_DIPPER/1.0'}});const id=r.data?.id;if(!id)throw new Error(r.data?.message||'Pixeldrain n’a pas renvoyé d’identifiant.');return{id,name:safe,view:`https://pixeldrain.com/u/${id}`,direct:`https://pixeldrain.com/api/file/${id}`,bytes:stat.size}}
function e(x){return`❌ *Upload Tools*\n${String(x?.response?.data?.message||x?.message||x).slice(0,700)}`}
const commands=[];
commands.push({name:'pixupload',aliases:['pixeldrainup'],category:CAT,description:'Uploader le fichier cité vers Pixeldrain',usage:'.pixupload',async execute(sock,msg,args,extra){let i;try{await extra.reply('☁️ Upload en cours…');i=await fileLab.getInput(msg);const u=await uploadPixeldrain(i.file,i.name);await extra.reply(`☁️ *Upload terminé*\n📄 ${u.name}\n💾 ${(u.bytes/1048576).toFixed(2)} Mo\n🔗 ${u.view}\n⬇️ Direct : ${u.direct}`)}catch(x){await extra.reply(e(x))}finally{fileLab.cleanup(i?.file)}}});
commands.push({name:'mirror',aliases:['reupload','urlmirror'],category:CAT,description:'Télécharger une URL publique sûre puis la réuploader',usage:'.mirror <url>',async execute(sock,msg,args,extra){let got;try{const raw=String(args[0]||'').trim();if(!raw)return extra.reply('⚠️ URL publique requise.');await extra.reply('🪞 Mirror : téléchargement sécurisé…');const direct=await engine.resolveUrl(raw);got=await engine.download(direct);await extra.reply('☁️ Mirror : upload…');const u=await uploadPixeldrain(got.file,got.fileName);await extra.reply(`🪞 *Mirror terminé*\n📄 ${u.name}\n💾 ${(u.bytes/1048576).toFixed(2)} Mo\n🔗 ${u.view}\n⬇️ Direct : ${u.direct}`)}catch(x){await extra.reply(e(x))}finally{engine.cleanup(got?.file)}}});
commands.push({name:'mirrorinfo',aliases:[],category:CAT,description:'Vérifier une URL avant mirror',usage:'.mirrorinfo <url>',async execute(sock,msg,args,extra){try{const raw=String(args[0]||'').trim(),r=await engine.headInfo(await engine.resolveUrl(raw));await extra.reply(`🪞 *Mirror Info*\n📄 ${r.fileName}\n🧩 ${r.contentType}\n💾 ${r.size?engine.human(r.size):'inconnue'}\n🌐 ${r.finalUrl}`)}catch(x){await extra.reply(e(x))}}});
module.exports=commands;