'use strict';
const config=require('../../config');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const bar=n=>Array.from({length:10},(_,i)=>i<n?'█':'░').join('');
function target(msg,args){const m=msg.message?.extendedTextMessage?.contextInfo?.mentionedJid||[];return m[0]?`@${String(m[0]).split('@')[0].split(':')[0]}`:String(args.join(' ')||'compte cible').slice(0,80);}
async function editOrSend(sock,jid,key,text,quoted){if(key){try{return await sock.sendMessage(jid,{text,edit:key});}catch(_){}}return sock.sendMessage(jid,{text},quoted?{quoted}:undefined);}
function prank({name,aliases,title,emoji,stages}){return{name,aliases,category:'🎮 Jeux & Fun',description:`Simulation humoristique de ${title.toLowerCase()} — aucun piratage réel.`,usage:`${config.prefix||'.'}${name} @cible`,async execute(sock,msg,args,extra){const t=target(msg,args);const first=await sock.sendMessage(extra.from,{text:`${emoji} *${title}*\nCible : ${t}\n\n[${bar(0)}] 0%`},extra.from?.endsWith('@g.us')?{quoted:msg}:undefined);const p=[10,27,46,68,84,100];for(let i=0;i<p.length;i++){await sleep(420+i*70);await editOrSend(sock,extra.from,first?.key,`${emoji} *${title}*\nCible : ${t}\n\n${stages[Math.min(i,stages.length-1)]}\n[${bar(Math.round(p[i]/10))}] ${p[i]}%`);}await sleep(350);return editOrSend(sock,extra.from,first?.key,`${emoji} *${title}*\nCible : ${t}\n\n[${bar(10)}] 100%\n\n🎭 *SIMULATION TERMINÉE*\nAucun compte, mot de passe, appareil, IP ou donnée réelle n’a été consulté, capturé ou modifié. C’était juste pour le fun 😈`);}};}
module.exports=[
prank({name:'fakehack',aliases:['hack','hackaccount','hackcompte'],emoji:'💻',title:'ACCOUNT BREACH SIMULATOR',stages:['Connexion au terminal fictif...','Recherche du profil...','Simulation de contournement...','Analyse de paquets imaginaires...','Synchronisation factice...','Accès fictif validé.']}),
prank({name:'crackpass',aliases:['fakepassword','passwordhack'],emoji:'🔐',title:'PASSWORD CRACK SIMULATOR',stages:['Chargement du dictionnaire fictif...','Test de combinaisons imaginaires...','Calcul de hash simulé...','Réduction de l’espace de recherche...','Dernière passe factice...','Mot de passe fictif trouvé.']}),
prank({name:'spyphone',aliases:['phonespy','fakephonehack'],emoji:'📱',title:'PHONE SPY SIMULATOR',stages:['Recherche du téléphone...','Handshake simulé...','Lecture fictive des capteurs...','Synchronisation imaginaire...','Compilation du rapport...','Canal fictif ouvert.']}),
prank({name:'traceip',aliases:['iptrack','faketrace'],emoji:'🌐',title:'IP TRACE SIMULATOR',stages:['Résolution fictive du réseau...','Scan imaginaire des routes...','Triangulation simulée...','Analyse des relais...','Calcul d’une position fictive...','Trace fictive terminée.']}),
prank({name:'clonesession',aliases:['sessionhack','fakeclone'],emoji:'🧬',title:'SESSION CLONE SIMULATOR',stages:['Lecture fictive de session...','Duplication imaginaire des jetons...','Vérification simulée...','Création d’un clone factice...','Synchronisation fantôme...','Clone fictif prêt.']})];
