'use strict';

const axios=require('axios');
const cheerio=require('cheerio');
const UA='Mozilla/5.0 (compatible; ExauceeResearch/2.0; +https://github.com/Tresor562/DIPPER-)';
const DEFAULT_TIMEOUT=9000;
function normalize(text=''){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();}
function stripTracking(url=''){try{const u=new URL(url);for(const key of[...u.searchParams.keys()])if(/^(utm_|fbclid|gclid|mc_)/i.test(key))u.searchParams.delete(key);u.hash='';return u.toString();}catch(_){return String(url||'');}}
function extractUrl(text=''){const m=String(text).match(/https?:\/\/[^\s<>"')\]]+/i);return m?stripTracking(m[0].replace(/[.,!?;:]+$/,'')):null;}
function words(text=''){return new Set(normalize(text).split(/[^a-z0-9]+/).filter(x=>x.length>2));}
function relevance(query,item){const q=words(query),t=words(`${item.title||''} ${item.snippet||''}`);if(!q.size)return 0;let hit=0;for(const w of q)if(t.has(w))hit++;return hit/q.size;}
function safeUrl(raw=''){try{const u=new URL(raw);if(!/^https?:$/.test(u.protocol))return null;if(/^(localhost|127\.|0\.0\.0\.0|169\.254\.|10\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/i.test(u.hostname))return null;return u.toString();}catch(_){return null;}}
function sourceQuality(url='',source=''){try{const h=new URL(url).hostname.toLowerCase();let q=0.45;if(/(?:^|\.)wikipedia\.org$/.test(h))q=0.72;if(/(?:^|\.)gov(?:\.[a-z]{2})?$|(?:^|\.)gouv\.[a-z]{2}$|(?:^|\.)edu$|(?:^|\.)ac\.[a-z]{2}$/.test(h))q=0.92;if(/(?:^|\.)who\.int$|(?:^|\.)un\.org$|(?:^|\.)europa\.eu$/.test(h))q=0.94;if(source==='direct-url')q=Math.max(q,0.65);return q;}catch(_){return 0.3;}}
function planQueries(query){const raw=String(query||'').replace(/https?:\/\/\S+/g,'').trim(),out=[raw];const n=normalize(raw);if(/\b(compare|comparaison|vs|contre)\b/.test(n)){const parts=raw.split(/\b(?:vs|contre)\b/i).map(x=>x.trim()).filter(Boolean);out.push(...parts);}if(/\b(actuel|actuelle|aujourd|recent|recente|derniere|dernier|maintenant)\b/.test(n))out.push(`${raw} date source officielle`);if(/\b(prix|tarif|cout|coût)\b/.test(n))out.push(`${raw} prix officiel`);if(/\b(comment|pourquoi|analyse|cause|fonctionne)\b/.test(n))out.push(`${raw} explication documentation`);return[...new Set(out.filter(x=>x.length>2))].slice(0,3);}
function sentenceFallback(report){const rows=(report?.results||[]).slice(0,6);if(!rows.length)return"Je n’ai trouvé aucune source exploitable pour cette recherche.";return`Voilà ce que j’ai pu recouper rapidement :\n\n${rows.map((r,i)=>`${i+1}. ${r.title}${r.snippet?` — ${String(r.snippet).replace(/\s+/g,' ').slice(0,340)}`:''}`).join('\n\n')}`;}
class ResearchEngine{
  constructor({timeout=DEFAULT_TIMEOUT,cacheTtlMs=10*60*1000,maxResults=10}={}){this.timeout=timeout;this.cacheTtlMs=cacheTtlMs;this.maxResults=maxResults;this.cache=new Map();this.http=axios.create({timeout,maxRedirects:4,headers:{'User-Agent':UA,'Accept-Language':'fr,en;q=0.8'}});}
  needsResearch(text=''){const t=normalize(text);if(extractUrl(text))return true;if(/\b(cherche|recherche|verifie|recoupe|trouve|sources?|actualite|aujourd'hui|maintenant|recent|derniere?s?|nouvelle?s?|prix|score|classement|meteo|qui est actuellement|en ce moment|lis ce lien|analyse ce lien|resume ce lien)\b/.test(t))return true;if(/^(?:qui\s+est|qui\s+sont|qu['’]?est[- ]ce\s+que|c['’]?est\s+qui|ou\s+se\s+trouve|où\s+se\s+trouve|quand\s+a\s+eu\s+lieu|quelle\s+est\s+la\s+capitale\s+de)\s+.{2,120}[? ]*$/.test(t))return true;return false;}
  async searchDuckDuckGo(query){const{data}=await this.http.get(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{responseType:'text'}),$=cheerio.load(data),out=[];$('.result').each((_,el)=>{if(out.length>=this.maxResults)return false;const a=$(el).find('.result__a').first(),snippet=$(el).find('.result__snippet').first().text().replace(/\s+/g,' ').trim();let href=a.attr('href')||'';try{const u=new URL(href,'https://duckduckgo.com');href=u.searchParams.get('uddg')||href;}catch(_){}const cleaned=safeUrl(stripTracking(href));if(cleaned)out.push({title:a.text().trim(),url:cleaned,snippet,source:'duckduckgo'});});return out;}
  async searchWikipedia(query,lang='fr'){const host=lang==='en'?'en':'fr',endpoint=`https://${host}.wikipedia.org/w/api.php`,{data}=await this.http.get(endpoint,{params:{action:'query',list:'search',srsearch:query,format:'json',origin:'*'}});return(data?.query?.search||[]).slice(0,5).map(row=>({title:row.title,url:`https://${host}.wikipedia.org/wiki/${encodeURIComponent(String(row.title).replace(/ /g,'_'))}`,snippet:cheerio.load(`<div>${row.snippet||''}</div>`).text(),source:'wikipedia'}));}
  async fetchPage(url){const safe=safeUrl(url);if(!safe)throw new Error('URL non autorisée');const{data,headers}=await this.http.get(safe,{responseType:'text'}),type=String(headers['content-type']||'');if(!/html|text\//i.test(type))return{title:safe,text:''};const $=cheerio.load(data);$('script,style,noscript,nav,footer,header,form,svg,canvas,aside').remove();const title=$('title').first().text().replace(/\s+/g,' ').trim(),root=$('article').first().length?$('article').first():$('main').first().length?$('main').first():$('body'),text=root.text().replace(/\s+/g,' ').trim().slice(0,22000);return{title,text};}
  async researchUrl(url){const safe=safeUrl(url);if(!safe)throw new Error('URL non autorisée');const page=await this.fetchPage(safe);return{query:safe,queries:[safe],searchedAt:Date.now(),directUrl:true,results:[{title:page.title||safe,url:safe,snippet:page.text.slice(0,700),content:page.text,source:'direct-url',relevance:1,quality:sourceQuality(safe,'direct-url'),score:1}]};}
  async research(query,{lang='fr',deep=true}={}){const direct=extractUrl(query);if(direct)return this.researchUrl(direct);const queries=planQueries(query),key=`${lang}:${normalize(query)}:${deep?1:0}`,cached=this.cache.get(key);if(cached&&cached.expiresAt>Date.now())return structuredClone(cached.value);const jobs=[];for(const q of queries){jobs.push(this.searchDuckDuckGo(q));jobs.push(this.searchWikipedia(q,lang));}const settled=await Promise.allSettled(jobs),merged=[],seen=new Map();for(const s of settled){if(s.status!=='fulfilled')continue;for(const item of s.value){const url=stripTracking(item.url);if(!url)continue;const prev=seen.get(url);if(prev){prev.hits=(prev.hits||1)+1;continue;}const quality=sourceQuality(url,item.source),rel=Math.max(...queries.map(q=>relevance(q,item)));const row={...item,url,relevance:rel,quality,hits:1};seen.set(url,row);merged.push(row);}}for(const r of merged)r.score=r.relevance*0.62+r.quality*0.28+Math.min(0.1,(r.hits-1)*0.05);merged.sort((a,b)=>b.score-a.score);const selected=[];const domains=new Map();for(const item of merged){let d='';try{d=new URL(item.url).hostname;}catch(_){}const used=domains.get(d)||0;if(used>=2)continue;domains.set(d,used+1);selected.push(item);if(selected.length>=this.maxResults)break;}if(deep)await Promise.all(selected.slice(0,6).map(async item=>{try{const page=await this.fetchPage(item.url);item.content=page.text;if(!item.title&&page.title)item.title=page.title;}catch(_){item.content='';}}));const result={query,queries,searchedAt:Date.now(),results:selected,coverage:{queries:queries.length,domains:new Set(selected.map(x=>{try{return new URL(x.url).hostname;}catch(_){return'';}})).size,sources:selected.length}};this.cache.set(key,{expiresAt:Date.now()+this.cacheTtlMs,value:result});if(this.cache.size>200)this.cache.delete(this.cache.keys().next().value);return structuredClone(result);}
  buildContext(report){return(report?.results||[]).slice(0,10).map((r,i)=>`[Source ${i+1}] ${r.title}\nURL: ${r.url}\nOrigine: ${r.source}\nQualité estimée: ${Math.round(Number(r.quality||0)*100)}/100\nPertinence: ${Math.round(Number(r.relevance||0)*100)}/100\nContenu: ${String(r.content||r.snippet||'').slice(0,3000)}`).join('\n\n');}
  sourceFooter(report,max=6){const rows=(report?.results||[]).slice(0,max);return rows.length?`Sources consultées :\n${rows.map((r,i)=>`${i+1}. ${r.title} — ${r.url}`).join('\n')}`:'';}
  fallbackSummary(report){return sentenceFallback(report);}
}
module.exports={ResearchEngine,safeUrl,relevance,stripTracking,extractUrl,sentenceFallback,sourceQuality,planQueries};
