'use strict';

const fs=require('fs');
const path=require('path');
const sanitize=v=>String(v||'').replace(/[^a-zA-Z0-9_@.+:-]/g,'_').slice(0,180);
const STOP=new Set('le la les un une des de du d et ou a au aux en pour par sur dans avec sans ce cet cette ces je tu il elle on nous vous ils elles mon ma mes ton ta tes son sa ses qui que quoi est sont etre être avoir ai as a avons avez ont me te se y ne pas plus tres très comme'.split(/\s+/));
function tokens(v=''){return String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!STOP.has(x));}
function words(v=''){return new Set(tokens(v));}
function relevance(value,query,ts=0){const A=tokens(value),B=tokens(query),setA=new Set(A),setB=new Set(B);let overlap=0;for(const w of setB)if(setA.has(w))overlap++;const lexical=setB.size?overlap/setB.size:0;let bigrams=0,total=Math.max(0,B.length-1);for(let i=0;i<B.length-1;i++){const pair=`${B[i]} ${B[i+1]}`;if(String(value).toLowerCase().includes(pair))bigrams++;}const phrase=total?bigrams/total:0,ageHours=Math.max(0,(Date.now()-Number(ts||0))/3600000),recency=1/(1+ageHours/72);return lexical*0.66+phrase*0.18+recency*0.16;}
class MemoryStore{
  constructor({root=path.join(process.cwd(),'data','exaucee')}={}){this.root=root;this.cache=new Map();}
  _scope(sessionId,chatId,userId){return[sanitize(sessionId||'default'),sanitize(chatId||'private'),sanitize(userId||'shared')].join('__');}
  _file(scope){return path.join(this.root,`${scope}.json`);}
  _load(scope){if(this.cache.has(scope))return this.cache.get(scope);let value={facts:[],episodes:[],goals:[],commitments:[],preferences:{},summary:'',summaryTurns:0,updatedAt:0};try{value={...value,...JSON.parse(fs.readFileSync(this._file(scope),'utf8'))};}catch(_){}for(const k of['facts','episodes','goals','commitments'])if(!Array.isArray(value[k]))value[k]=[];this.cache.set(scope,value);return value;}
  getContext(ids){return structuredClone(this._load(this._scope(ids.sessionId,ids.chatId,ids.userId)));}
  getRelevantContext(ids,query='',limits={}){const state=this._load(this._scope(ids.sessionId,ids.chatId,ids.userId)),cfg={facts:18,episodes:20,goals:10,commitments:10,...limits};const rank=(rows,limit)=>[...(rows||[])].map((x,i)=>({...x,_score:relevance(x.value,query,x.ts),_i:i})).sort((a,b)=>b._score-a._score||b._i-a._i).slice(0,Math.max(1,limit)).sort((a,b)=>Number(a.ts||0)-Number(b.ts||0)).map(({_score,_i,...x})=>x);return structuredClone({...state,facts:rank(state.facts,cfg.facts),episodes:rank(state.episodes,cfg.episodes),goals:rank(state.goals,cfg.goals),commitments:rank(state.commitments,cfg.commitments)});}
  remember(ids,item){if(!item||!item.value)return false;const scope=this._scope(ids.sessionId,ids.chatId,ids.userId),state=this._load(scope);const bucket=item.type==='episode'?'episodes':item.type==='goal'?'goals':item.type==='commitment'?'commitments':'facts',value=String(item.value).slice(0,3000),rows=state[bucket];if(!rows.slice(-50).some(x=>String(x.value)===value))rows.push({value,source:item.source||'conversation',status:item.status||'active',ts:Date.now()});const limits={episodes:600,facts:350,goals:120,commitments:120};state[bucket]=rows.slice(-(limits[bucket]||250));state.updatedAt=Date.now();this._persist(scope,state);return true;}
  resolve(ids,type,needle=''){const scope=this._scope(ids.sessionId,ids.chatId,ids.userId),state=this._load(scope),bucket=type==='goal'?'goals':'commitments',q=words(needle);let best=null,bestScore=-1;for(const row of state[bucket]){if(row.status==='done')continue;const sc=relevance(row.value,needle,row.ts)+(q.size?0:0.2);if(sc>bestScore){best=row;bestScore=sc;}}if(!best)return false;best.status='done';best.resolvedAt=Date.now();this._persist(scope,state);return true;}
  setPreference(ids,key,value){const scope=this._scope(ids.sessionId,ids.chatId,ids.userId),state=this._load(scope);state.preferences[sanitize(key)]=value;state.updatedAt=Date.now();this._persist(scope,state);}
  updateSummary(ids,userText,assistantText){const scope=this._scope(ids.sessionId,ids.chatId,ids.userId),state=this._load(scope);state.summaryTurns=Number(state.summaryTurns||0)+1;const important=[],u=String(userText||'').replace(/\s+/g,' ').trim(),a=String(assistantText||'').replace(/\s+/g,' ').trim();if(u)important.push(`U: ${u.slice(0,520)}`);if(a)important.push(`E: ${a.slice(0,520)}`);state.summary=[...String(state.summary||'').split('\n').filter(Boolean),...important].slice(-40).join('\n').slice(-14000);state.updatedAt=Date.now();this._persist(scope,state);return state.summary;}
  clearConversation(ids,{keepFacts=true,keepGoals=true}={}){const scope=this._scope(ids.sessionId,ids.chatId,ids.userId),state=this._load(scope);state.episodes=[];state.summary='';state.summaryTurns=0;if(!keepFacts)state.facts=[];if(!keepGoals){state.goals=[];state.commitments=[];}state.updatedAt=Date.now();this._persist(scope,state);}
  _persist(scope,state){fs.mkdirSync(this.root,{recursive:true});const target=this._file(scope),tmp=`${target}.tmp`;fs.writeFileSync(tmp,JSON.stringify(state,null,2));fs.renameSync(tmp,target);}
}
module.exports={MemoryStore,relevance};
