'use strict';
const axios=require('axios');
const config=require('../../config');
const {sendMediaCarousel}=require('../../utils/interactiveCarousel');
const API='https://api.nexray.web.id';
const UA='Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 Chrome/126 Mobile Safari/537.36';
function firstString(...values){for(const value of values){if(typeof value==='string'&&/^https?:\/\//i.test(value))return value;if(Array.isArray(value)){const found=value.find(v=>typeof v==='string'&&/^https?:\/\//i.test(v));if(found)return found;}}return ''}
function extractArray(data){for(const c of [data,data?.result,data?.results,data?.data,data?.data?.result,data?.data?.results,data?.result?.data,data?.result?.results])if(Array.isArray(c))return c;if(data&&typeof data==='object')for(const v of Object.values(data))if(Array.isArray(v))return v;return []}
function normalizeResult(item,mode,index){if(typeof item==='string')return{type:'image',mediaUrl:item,title:`Résultat ${index+1}`,url:item};const image=firstString(item?.image,item?.image_url,item?.imageUrl,item?.thumbnail,item?.thumb,item?.cover,item?.cover_url,item?.origin_cover,item?.dynamic_cover,item?.images,item?.src,item?.photo);const video=firstString(item?.play,item?.play_url,item?.playUrl,item?.video,item?.video_url,item?.videoUrl,item?.nowm,item?.no_watermark,item?.download);const original=firstString(item?.url,item?.link,item?.web_url,item?.webUrl,item?.share_url,item?.shareUrl,item?.source,item?.original);const title=String(item?.title||item?.desc||item?.description||item?.caption||item?.name||`Résultat ${index+1}`).slice(0,120);const author=String(item?.author?.nickname||item?.author?.name||item?.username||item?.channel||'').trim();const body=author?`👤 ${author}`:'';if(mode==='video'&&video)return{type:'video',mediaUrl:video,title,body,url:original||video};if(image)return{type:'image',mediaUrl:image,title,body,url:original||image};if(video)return{type:'video',mediaUrl:video,title,body,url:original||video};return null}
function decodeHtml(s){return String(s||'').replace(/&quot;/g,'"').replace(/&#34;/g,'"').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>')}
async function nexray(endpoint,query){const r=await axios.get(`${API}${endpoint}`,{params:{q:query},timeout:14000,headers:{'User-Agent':'THE-BIG-DIPPER/1.0'}});return extractArray(r.data)}
async function bingImages(query){const r=await axios.get('https://www.bing.com/images/search',{params:{q:query,form:'HDRSC3'},timeout:18000,headers:{'User-Agent':UA,'Accept-Language':'fr-FR,fr;q=0.9,en;q=0.8'}});const html=String(r.data||'');const out=[];const re=/<a[^>]+class=["'][^"']*iusc[^"']*["'][^>]+m=["']([^"']+)["']/gi;let m;while((m=re.exec(html))&&out.length<16){try{const j=JSON.parse(decodeHtml(m[1]));const image=firstString(j.murl,j.turl);if(!image)continue;out.push({image,thumbnail:j.turl,url:firstString(j.purl,j.murl),title:decodeHtml(j.tit||j.desc||`Résultat ${out.length+1}`)})}catch(_){}}return out}
async function searchResilient(endpoint,primaryQuery,fallbackQuery){let primaryError=null;try{const a=await nexray(endpoint,primaryQuery);if(a.length)return a}catch(e){primaryError=e}try{const b=await bingImages(fallbackQuery||primaryQuery);if(b.length)return b}catch(e){if(!primaryError)primaryError=e}if(primaryError)throw primaryError;return []}
function fallbackQuery(label,q){const l=label.toLowerCase();if(l.includes('pinterest'))return `site:pinterest.com ${q}`;if(l.includes('tiktok'))return `site:tiktok.com ${q}`;if(l.includes('facebook'))return `site:facebook.com ${q}`;if(l.includes('instagram'))return `site:instagram.com ${q}`;if(l.includes('twitter')||l==='x')return `site:x.com ${q}`;return q}
function makeCommand({name,aliases=[],label,endpoint,mode='image',queryTransform=q=>q}){return{name,aliases,category:'📥 Téléchargements',description:`Recherche ${label} et affiche jusqu’à 10 résultats dans un carrousel horizontal.`,usage:`${config.prefix||'.'}${name} <recherche>`,async execute(sock,msg,args,extra){const query=args.join(' ').trim();if(!query)return extra.reply(`🔎 Usage : ${config.prefix||'.'}${name} <ce que tu cherches>`);let wait;try{wait=await sock.sendMessage(extra.from,{text:`🔎 Recherche ${label} : *${query}*…`},extra.from?.endsWith('@g.us')?{quoted:msg}:undefined);const transformed=queryTransform(query);const raw=await searchResilient(endpoint,transformed,fallbackQuery(label,query));const items=raw.map((x,i)=>normalizeResult(x,mode,i)).filter(Boolean).slice(0,10);if(!items.length)throw new Error('Aucun média exploitable trouvé.');try{if(wait?.key)await sock.sendMessage(extra.from,{delete:wait.key})}catch(_){}return sendMediaCarousel(sock,extra.from,{title:`🔎 ${label} — ${query}`,subtitle:`${items.length} résultat(s) • glisse vers la gauche pour parcourir`,items,quoted:extra.from?.endsWith('@g.us')?msg:null})}catch(error){try{if(wait?.key)await sock.sendMessage(extra.from,{delete:wait.key})}catch(_){}return extra.reply(`❌ Recherche ${label} impossible : ${String(error?.message||error).slice(0,180)}`)}}}}
module.exports=[
makeCommand({name:'pinterest2',aliases:['pinterestsearch','pinsearch'],label:'Pinterest',endpoint:'/search/pinterest'}),
makeCommand({name:'tiktoksearch',aliases:['tiktok2','ttsearch'],label:'TikTok',endpoint:'/search/tiktok',mode:'video'}),
makeCommand({name:'youtubesearch',aliases:['ytsearch2','youtube2'],label:'YouTube',endpoint:'/search/youtube'}),
makeCommand({name:'soundcloudsearch',aliases:['scsearch'],label:'SoundCloud',endpoint:'/search/soundcloud'}),
makeCommand({name:'spotifysearch',aliases:['spsearch'],label:'Spotify',endpoint:'/search/spotify'}),
makeCommand({name:'bilibilisearch',aliases:['bbsearch'],label:'Bilibili',endpoint:'/search/bilibili'}),
makeCommand({name:'instagramsearch',aliases:['igsearch'],label:'Instagram',endpoint:'/search/googleimage',queryTransform:q=>`site:instagram.com ${q}`}),
makeCommand({name:'facebooksearch',aliases:['fbsearch'],label:'Facebook',endpoint:'/search/googleimage',queryTransform:q=>`site:facebook.com ${q}`}),
makeCommand({name:'xsearch',aliases:['twittersearch'],label:'X / Twitter',endpoint:'/search/googleimage',queryTransform:q=>`site:x.com ${q}`})];
