'use strict';

const fs = require('fs');
const path = require('path');

const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
const uid=(p='event')=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const clone=v=>structuredClone(v);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();

function rankScores(scores={}) { return Object.entries(scores).map(([userId,score])=>({userId,score:Number(score)||0})).sort((a,b)=>b.score-a.score || String(a.userId).localeCompare(String(b.userId))).map((x,i)=>({...x,rank:i+1})); }
function defaultRewards(count=3) { return [{rank:1,label:'🥇 Champion',points:100},{rank:2,label:'🥈 Vice-champion',points:60},{rank:3,label:'🥉 Troisième',points:35}].slice(0,clamp(count,1,3)); }
function balancedTeams(players=[], teamCount=2) { const n=clamp(teamCount,2,16); const teams=Array.from({length:n},(_,i)=>({id:`team_${i+1}`,name:`Équipe ${i+1}`,members:[],score:0})); players.forEach((p,i)=>teams[i%n].members.push(p)); return teams; }

class TournamentDirector {
  constructor({file=path.join(process.cwd(),'data','exaucee','events.json'), scheduler=null}={}) { this.file=file; this.scheduler=scheduler; this.events=new Map(); this._load(); }
  _load(){try{const raw=JSON.parse(fs.readFileSync(this.file,'utf8'));for(const e of raw?.events||raw||[])if(e?.id)this.events.set(e.id,e);}catch(_){} }
  _save(){fs.mkdirSync(path.dirname(this.file),{recursive:true});const tmp=`${this.file}.tmp`;fs.writeFileSync(tmp,JSON.stringify({version:3,events:[...this.events.values()]},null,2));fs.renameSync(tmp,this.file);}
  _put(e){e.updatedAt=Date.now();this.events.set(e.id,e);this._save();return clone(e);}
  _credit(e,userId,points){const p=Number(points)||0;e.scores[userId]=Number(e.scores[userId]||0)+p;if(e.teamMode&&Array.isArray(e.teams)){const team=e.teams.find(t=>Array.isArray(t.members)&&t.members.includes(userId));if(team)team.score=Number(team.score||0)+p;}return e.scores[userId];}
  list(chatId,{activeOnly=false}={}){return [...this.events.values()].filter(e=>e.chatId===chatId).filter(e=>!activeOnly||!['finished','cancelled'].includes(e.status)).sort((a,b)=>(a.startAt||a.createdAt)-(b.startAt||b.createdAt)).map(clone);}
  get(chatId,ref){const q=String(ref||'').replace(/^#/,'').toLowerCase();return this.list(chatId).find(e=>e.id===ref||String(e.alias).toLowerCase()===q||String(e.id).endsWith(q))||null;}
  create(chatId,spec={}){const id=uid('event'),alias=id.slice(-6),format=spec.format||'points';const event={id,alias,chatId,title:spec.title||'Événement Exaucée',description:spec.description||'',theme:spec.theme||'général',gameType:spec.gameType||'custom',format,status:'scheduled',createdBy:spec.by||null,createdAt:Date.now(),startAt:Number(spec.startAt)||Date.now(),registrationOpensAt:Number(spec.registrationOpensAt)||Date.now(),registrationClosesAt:Number(spec.registrationClosesAt)||Number(spec.startAt)||Date.now(),maxPlayers:clamp(spec.maxPlayers||500,2,5000),minPlayers:clamp(spec.minPlayers||2,1,5000),teamMode:Boolean(spec.teamMode),teamCount:clamp(spec.teamCount||2,2,16),players:{},teams:[],rounds:Array.isArray(spec.rounds)?spec.rounds:[],currentRound:0,scores:{},roundResponses:{},history:[],rewards:Array.isArray(spec.rewards)&&spec.rewards.length?spec.rewards:defaultRewards(),rules:Array.isArray(spec.rules)?spec.rules:[],autoStart:spec.autoStart!==false,lateJoin:Boolean(spec.lateJoin),metadata:spec.metadata||{}};this._put(event);this._scheduleLifecycle(event);return clone(event);}
  _scheduleLifecycle(event){if(!this.scheduler)return;const base=`gameevent:${event.id}`;this.scheduler.schedule({id:`${base}:open`,runAt:Math.max(Date.now()+1000,event.registrationOpensAt),action:{type:'game_event',eventId:event.id,chatId:event.chatId,op:'open_registration'}});this.scheduler.schedule({id:`${base}:start`,runAt:Math.max(Date.now()+1000,event.startAt),action:{type:'game_event',eventId:event.id,chatId:event.chatId,op:'start'}});}
  _scheduleRoundTimeout(e){if(!this.scheduler||e.status!=='playing')return;const round=e.rounds[e.currentRound];if(!round)return;const sec=clamp(round.timeLimitSec||30,5,600);this.scheduler.schedule({id:`gameevent:${e.id}:round:${e.currentRound}:timeout`,runAt:Date.now()+sec*1000,action:{type:'game_event',eventId:e.id,chatId:e.chatId,op:'round_timeout',roundIndex:e.currentRound}});}
  register(chatId,eventRef,userId,profile={}){const snap=this.get(chatId,eventRef);if(!snap)return{ok:false,reason:'not_found'};const e=this.events.get(snap.id);if(!['scheduled','registration'].includes(e.status))return{ok:false,reason:'closed'};if(Date.now()>e.registrationClosesAt&&!e.lateJoin)return{ok:false,reason:'closed'};if(Object.keys(e.players).length>=e.maxPlayers)return{ok:false,reason:'full'};e.players[userId]={userId,name:profile.name||'',joinedAt:Date.now(),active:true};e.scores[userId]??=0;this._put(e);return{ok:true,event:clone(e),count:Object.keys(e.players).length};}
  unregister(chatId,eventRef,userId){const snap=this.get(chatId,eventRef);if(!snap)return false;const e=this.events.get(snap.id);if(!e.players[userId])return false;delete e.players[userId];delete e.scores[userId];this._put(e);return true;}
  start(chatId,eventRef){const snap=this.get(chatId,eventRef);if(!snap)return{ok:false,reason:'not_found'};const e=this.events.get(snap.id),players=Object.keys(e.players);if(players.length<e.minPlayers){e.status='waiting_players';this._put(e);return{ok:false,reason:'not_enough_players',count:players.length,min:e.minPlayers,event:clone(e)};}e.status='playing';e.startedAt=Date.now();if(e.teamMode&&!e.teams.length)e.teams=balancedTeams(players,e.teamCount);if(!e.rounds.length)e.rounds=[{id:'round_1',name:'Manche 1',type:e.gameType,status:'ready',points:1,timeLimitSec:30}];e.currentRound=0;e.rounds[0].status='playing';e.rounds[0].startedAt=Date.now();e.roundResponses['0']={};e.history.push({type:'start',ts:Date.now(),players:players.length});this._put(e);this._scheduleRoundTimeout(e);return{ok:true,event:clone(e),round:e.rounds[0]};}
  score(chatId,eventRef,userId,points=1,reason=''){const snap=this.get(chatId,eventRef);if(!snap)return null;const e=this.events.get(snap.id);this._credit(e,userId,points);e.history.push({type:'score',userId,points:Number(points||0),reason:String(reason||'').slice(0,180),ts:Date.now()});e.history=e.history.slice(-5000);this._put(e);return{score:e.scores[userId],ranking:rankScores(e.scores).slice(0,20),event:clone(e)};}
  submitQuizAnswer(chatId,eventRef,userId,answer){const snap=this.get(chatId,eventRef);if(!snap||snap.status!=='playing'||snap.gameType!=='quiz')return{handled:false};const e=this.events.get(snap.id),idx=e.currentRound,round=e.rounds[idx];if(!round)return{handled:false};e.roundResponses[String(idx)]??={};if(e.roundResponses[String(idx)][userId])return{handled:true,duplicate:true,correct:false,event:clone(e)};const ts=Date.now(),answers=Array.isArray(round.answers)?round.answers:[];const correct=answers.some(a=>norm(a)===norm(answer));const previousCorrect=Object.values(e.roundResponses[String(idx)]).filter(x=>x.correct).length;let points=0;if(correct){const base=Number(round.points||1);const speedBonus=previousCorrect===0?2:previousCorrect<3?1:0;points=base+speedBonus;this._credit(e,userId,points);}e.roundResponses[String(idx)][userId]={answer:String(answer).slice(0,300),correct,points,ts};e.history.push({type:'answer',round:idx+1,userId,correct,points,ts});e.history=e.history.slice(-10000);this._put(e);return{handled:true,duplicate:false,correct,points,round:idx+1,event:clone(e),ranking:rankScores(e.scores).slice(0,10)};}
  submitJudgedAnswer(chatId,eventRef,userId,answer,verdict={}){const snap=this.get(chatId,eventRef);if(!snap||snap.status!=='playing')return{handled:false};const e=this.events.get(snap.id),idx=e.currentRound,round=e.rounds[idx];if(!round)return{handled:false};e.roundResponses[String(idx)]??={};if(e.roundResponses[String(idx)][userId])return{handled:true,duplicate:true,event:clone(e)};const mode=round.mode||'ai_judge';let accepted=Boolean(verdict.accepted),points=Math.max(0,Math.min(Number(round.points||1),Number(verdict.points)||0));if(mode==='participation'){accepted=true;points=Number(round.points||1);}if(mode==='first_response'){const hasWinner=Object.values(e.roundResponses[String(idx)]).some(r=>r.accepted&&r.points>0);accepted=!hasWinner;points=accepted?Number(round.points||1):0;}if(mode==='vote'){accepted=true;points=0;}if(accepted&&points)this._credit(e,userId,points);e.roundResponses[String(idx)][userId]={answer:String(answer).slice(0,1500),accepted,points,feedback:String(verdict.feedback||'').slice(0,300),ts:Date.now()};e.history.push({type:'judged_answer',round:idx+1,userId,accepted,points,mode,ts:Date.now()});e.history=e.history.slice(-10000);this._put(e);return{handled:true,duplicate:false,accepted,points,feedback:String(verdict.feedback||''),event:clone(e),ranking:rankScores(e.scores).slice(0,10)};}
  nextRound(chatId,eventRef){const snap=this.get(chatId,eventRef);if(!snap)return{ok:false};const e=this.events.get(snap.id);if(e.rounds[e.currentRound]){e.rounds[e.currentRound].status='finished';e.rounds[e.currentRound].finishedAt=Date.now();}e.currentRound+=1;if(e.currentRound>=e.rounds.length)return this.finish(chatId,eventRef);e.rounds[e.currentRound].status='playing';e.rounds[e.currentRound].startedAt=Date.now();e.roundResponses[String(e.currentRound)]={};e.history.push({type:'round',round:e.currentRound+1,ts:Date.now()});this._put(e);this._scheduleRoundTimeout(e);return{ok:true,finished:false,event:clone(e),round:e.rounds[e.currentRound]};}
  finish(chatId,eventRef){const snap=this.get(chatId,eventRef);if(!snap)return{ok:false};const e=this.events.get(snap.id);e.status='finished';e.finishedAt=Date.now();e.ranking=rankScores(e.scores);e.teamRanking=(e.teams||[]).map(t=>({id:t.id,name:t.name,score:Number(t.score||0)})).sort((a,b)=>b.score-a.score).map((x,i)=>({...x,rank:i+1}));e.awards=e.rewards.map(r=>{const winner=e.ranking.find(x=>x.rank===r.rank);return winner?{...r,userId:winner.userId,score:winner.score}:null;}).filter(Boolean);e.history.push({type:'finish',ts:Date.now()});this._put(e);return{ok:true,finished:true,event:clone(e),ranking:clone(e.ranking),teamRanking:clone(e.teamRanking),awards:clone(e.awards)};}
  cancel(chatId,eventRef){const snap=this.get(chatId,eventRef);if(!snap)return null;const e=this.events.get(snap.id);e.status='cancelled';e.cancelledAt=Date.now();this._put(e);for(const t of this.scheduler?.list?.({status:'pending'})||[])if(t.id.startsWith(`gameevent:${e.id}:`))this.scheduler.cancel(t.id);return clone(e);}
  standings(chatId,eventRef,limit=20){const snap=this.get(chatId,eventRef);if(!snap)return[];return rankScores(snap.scores).slice(0,clamp(limit,1,100));}
  teamStandings(chatId,eventRef){const snap=this.get(chatId,eventRef);if(!snap)return[];return (snap.teams||[]).map(t=>({id:t.id,name:t.name,score:Number(t.score||0)})).sort((a,b)=>b.score-a.score).map((x,i)=>({...x,rank:i+1}));}
  _roundAnnouncement(e,round){const base=`🎯 *${e.title} — ${round.name}*\n#${e.alias}`;if(e.gameType==='quiz')return`${base}\n\n${round.prompt||'Question'}\n⏱️ ${round.timeLimitSec||30}s`;return`${base}\n\n${round.prompt||'La manche commence.'}\n⏱️ ${round.timeLimitSec||60}s`;}
  _finalText(e){const top=rankScores(e.scores).slice(0,10);const board=top.length?top.map(x=>`${x.rank}. @${String(x.userId).split('@')[0]} — ${x.score} pts`).join('\n'):'Aucun score.';const teams=e.teamMode?(e.teamRanking||this.teamStandings(e.chatId,e.id)).slice(0,5).map(x=>`${x.rank}. ${x.name} — ${x.score} pts`).join('\n'):'';const awards=(e.awards||[]).map(a=>`${a.label} : @${String(a.userId).split('@')[0]}`).join('\n');return`🏁 *${e.title} terminé !*\n\n🏆 *Classement*\n${board}${teams?`\n\n👥 *Équipes*\n${teams}`:''}${awards?`\n\n🎁 *Récompenses*\n${awards}`:''}`;}
  async handleScheduledTask(task,{send}={}){const a=task?.action||{},e=[...this.events.values()].find(x=>x.id===a.eventId);if(!e)return{ignored:true};if(a.op==='open_registration'){if(e.status==='scheduled')e.status='registration';this._put(e);await send?.(e.chatId,`🎮 *${e.title}* — inscriptions ouvertes !\nID : #${e.alias}\nDébut : ${new Date(e.startAt).toLocaleString('fr-FR')}\nPlaces : ${e.maxPlayers}\n\nÉcris *je participe #${e.alias}* pour t’inscrire.`);return{opened:true,eventId:e.id};}if(a.op==='start'){const r=this.start(e.chatId,e.id);if(!r.ok){await send?.(e.chatId,`⏳ *${e.title}* attend encore des joueurs (${r.count}/${r.min}).`);return r;}await send?.(e.chatId,`🚀 *${e.title} commence maintenant !*\nParticipants : ${Object.keys(r.event.players).length}\nFormat : ${r.event.format}`);await send?.(e.chatId,this._roundAnnouncement(r.event,r.round));return r;}if(a.op==='round_timeout'){if(e.status!=='playing'||e.currentRound!==Number(a.roundIndex))return{ignored:true};const r=this.nextRound(e.chatId,e.id);if(r.finished){await send?.(e.chatId,this._finalText(r.event));return r;}await send?.(e.chatId,this._roundAnnouncement(r.event,r.round));return r;}return{ignored:true};}
}

module.exports={TournamentDirector,rankScores,balancedTeams,defaultRewards};
