'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');const AdmZip=require('adm-zip');const AppInfoParser=require('app-info-parser');
function hash(data,algo='sha256'){return crypto.createHash(algo).update(data).digest('hex')}
function readZip(file){const z=new AdmZip(file);const entries=z.getEntries();return{z,entries}}
function signatureSummary(file){const buf=fs.readFileSync(file),{entries}=readZip(file);const certs=entries.filter(e=>/^META-INF\/.*\.(RSA|DSA|EC)$/i.test(e.entryName));const magic=Buffer.from('APK Sig Block 42');const hasV2Plus=buf.indexOf(magic)>=0;return{v1:certs.length>0,v2plus:hasV2Plus,certFiles:certs.map(e=>({name:e.entryName,sha256:hash(e.getData())})),sha256:hash(buf)} }
async function parseApk(file){const parser=new AppInfoParser(file);const result=await parser.parse();const {entries}=readZip(file);const dex=entries.filter(e=>/^classes\d*\.dex$/i.test(e.entryName));const libs=entries.filter(e=>/^lib\/[^/]+\/[^/]+\.so$/i.test(e.entryName));const abis=[...new Set(libs.map(e=>e.entryName.split('/')[1]))];const sig=signatureSummary(file);return{type:'APK',name:result.application?.label||result.label||result.name||null,packageName:result.package||result.packageName||result.applicationId||null,versionName:result.versionName||null,versionCode:result.versionCode||null,minSdk:result.usesSdk?.minSdkVersion||result.minSdkVersion||null,targetSdk:result.usesSdk?.targetSdkVersion||result.targetSdkVersion||null,permissions:Array.isArray(result.usesPermissions)?result.usesPermissions:(result.permission||result.permissions||[]),icon:result.icon||null,dexCount:dex.length,abis,fileCount:entries.length,signature:sig,raw:result}}
function parseXapk(file){const {z,entries}=readZip(file);const manifestEntry=entries.find(e=>/^manifest\.json$/i.test(e.entryName));let manifest=null;if(manifestEntry){try{manifest=JSON.parse(manifestEntry.getData().toString('utf8'))}catch(_){}}const apks=entries.filter(e=>/\.apk$/i.test(e.entryName));return{type:'XAPK',packageName:manifest?.package_name||manifest?.packageName||null,name:manifest?.name||null,versionName:manifest?.version_name||manifest?.versionName||null,versionCode:manifest?.version_code||manifest?.versionCode||null,minSdk:manifest?.min_sdk_version||null,targetSdk:manifest?.target_sdk_version||null,apkFiles:apks.map(e=>({name:e.entryName,bytes:e.header.size,sha256:hash(e.getData())})),obbFiles:entries.filter(e=>/\.obb$/i.test(e.entryName)).map(e=>e.entryName),fileCount:entries.length,manifest}}
async function analyze(file,name=''){const ext=path.extname(name||file).toLowerCase();if(ext==='.xapk'||ext==='.apks')return parseXapk(file);return parseApk(file)}
function verify(file,name=''){const {entries}=readZip(file);const names=new Set(entries.map(e=>e.entryName));const ext=path.extname(name||file).toLowerCase();if(ext==='.xapk'||ext==='.apks'){const apks=entries.filter(e=>/\.apk$/i.test(e.entryName));return{valid:apks.length>0,kind:'XAPK',checks:{zipReadable:true,hasApk:apks.length>0,hasManifest:names.has('manifest.json')},sha256:hash(fs.readFileSync(file))}}const sig=signatureSummary(file);const checks={zipReadable:true,hasManifest:names.has('AndroidManifest.xml'),hasDex:[...names].some(n=>/^classes\d*\.dex$/i.test(n)),hasSignature:sig.v1||sig.v2plus};return{valid:checks.hasManifest&&checks.hasDex,kind:'APK',checks,signature:sig,sha256:sig.sha256}}
function extract(file,outDir){const {z,entries}=readZip(file);fs.mkdirSync(outDir,{recursive:true});const files=[];for(const e of entries){if(e.isDirectory)continue;const base=path.basename(e.entryName);if(!base)continue;const dest=path.join(outDir,base);fs.writeFileSync(dest,e.getData());files.push(dest)}return files}
module.exports={analyze,verify,extract,signatureSummary,parseXapk};