'use strict';

const fs=require('fs');const os=require('os');const path=require('path');const crypto=require('crypto');const {execFile}=require('child_process');
const ffmpegPath=require('ffmpeg-static');const sharp=require('sharp');const PDFDocument=require('pdfkit');const AdmZip=require('adm-zip');const Seven=require('node-7z');const sevenBin=require('7zip-bin');const {createExtractorFromData}=require('node-unrar-js');const {downloadContentFromMessage}=require('@whiskeysockets/baileys');
const MAX_BYTES=Number(process.env.FILE_LAB_MAX_BYTES||45*1024*1024),TIMEOUT=Number(process.env.FILE_LAB_TIMEOUT_MS||180000);
function tmp(ext='bin'){return path.join(os.tmpdir(),`dipper-file-${process.pid}-${Date.now()}-${crypto.randomBytes(5).toString('hex')}.${ext}`)}
function dir(){const d=fs.mkdtempSync(path.join(os.tmpdir(),'dipper-dir-'));return d}
function unwrap(message){let m=message||{};for(let i=0;i<5;i++){if(m.ephemeralMessage?.message){m=m.ephemeralMessage.message;continue}if(m.viewOnceMessage?.message){m=m.viewOnceMessage.message;continue}if(m.viewOnceMessageV2?.message){m=m.viewOnceMessageV2.message;continue}if(m.documentWithCaptionMessage?.message){m=m.documentWithCaptionMessage.message;continue}break}return m}
function node(msg){const own=unwrap(msg?.message),quoted=unwrap(own?.extendedTextMessage?.contextInfo?.quotedMessage),m=quoted&&Object.keys(quoted).length?quoted:own;if(m.documentMessage)return{n:m.documentMessage,t:'document',name:m.documentMessage.fileName||'file.bin',mime:m.documentMessage.mimetype||'application/octet-stream'};if(m.imageMessage)return{n:m.imageMessage,t:'image',name:'image.jpg',mime:m.imageMessage.mimetype||'image/jpeg'};if(m.videoMessage)return{n:m.videoMessage,t:'video',name:'video.mp4',mime:m.videoMessage.mimetype||'video/mp4'};if(m.audioMessage)return{n:m.audioMessage,t:'audio',name:'audio.ogg',mime:m.audioMessage.mimetype||'audio/ogg'};if(m.stickerMessage)return{n:m.stickerMessage,t:'sticker',name:'sticker.webp',mime:'image/webp'};return null}
async function getInput(msg){const i=node(msg);if(!i)throw new Error('Réponds à un fichier ou média.');const stream=await downloadContentFromMessage(i.n,i.t),chunks=[];let total=0;for await(const c of stream){total+=c.length;if(total>MAX_BYTES)throw new Error(`Fichier trop volumineux (${Math.ceil(MAX_BYTES/1048576)} Mo max).`);chunks.push(c)}const ext=path.extname(i.name).slice(1)||mimeExt(i.mime);const f=tmp(ext);fs.writeFileSync(f,Buffer.concat(chunks));return{file:f,name:safeName(i.name),mime:i.mime,bytes:total}}
function mimeExt(m){m=String(m||'');if(m.includes('png'))return'png';if(m.includes('webp'))return'webp';if(m.includes('jpeg'))return'jpg';if(m.includes('pdf'))return'pdf';if(m.includes('mp4'))return'mp4';if(m.includes('mpeg'))return'mp3';return'bin'}
function safeName(n){return path.basename(String(n||'file.bin')).replace(/[^\w.()\- ]+/g,'_').slice(0,120)||'file.bin'}
function run(bin,args,timeout=TIMEOUT){return new Promise((res,rej)=>execFile(bin,args,{timeout,maxBuffer:8*1024*1024},(e,o,se)=>e?rej(new Error(String(se||e.message).trim().slice(0,900))):res({stdout:o,stderr:se})))}
async function imageConvert(input,format,opts={}){let s=sharp(input,{animated:true}).rotate();if(opts.width||opts.height)s=s.resize(opts.width||null,opts.height||null,{fit:'inside',withoutEnlargement:true});if(opts.rotate)s=s.rotate(Number(opts.rotate)||0);if(opts.grayscale)s=s.grayscale();const q=Math.max(20,Math.min(100,Number(opts.quality)||82));let ext=format;if(format==='jpg'||format==='jpeg'){ext='jpg';s=s.jpeg({quality:q})}else if(format==='png')s=s.png({compressionLevel:9});else if(format==='webp')s=s.webp({quality:q});else if(format==='avif')s=s.avif({quality:q});else throw new Error('Format image non supporté.');const out=tmp(ext);await s.toFile(out);return out}
async function videoConvert(input,format,opts={}){const ext=format==='audio'?'mp3':format;const out=tmp(ext);const a=['-hide_banner','-loglevel','error','-y','-i',input];if(format==='mp3'||format==='audio')a.push('-vn','-c:a','libmp3lame','-b:a',String(opts.bitrate||192)+'k');else if(format==='ogg')a.push('-vn','-c:a','libvorbis','-q:a','5');else if(format==='wav')a.push('-vn','-c:a','pcm_s16le');else if(format==='webm')a.push('-c:v','libvpx-vp9','-crf','34','-b:v','0','-c:a','libopus');else if(format==='gif')a.push('-vf',`fps=${Math.max(5,Math.min(20,Number(opts.fps)||12))},scale='min(640,iw)':-1:flags=lanczos`,'-t','12');else a.push('-c:v','libx264','-preset','veryfast','-crf',String(Math.max(18,Math.min(35,Number(opts.crf)||27))),'-c:a','aac','-b:a','128k');a.push(out);await run(ffmpegPath,a);return out}
async function imagesToPdf(files){if(!files.length)throw new Error('Aucune image.');const out=tmp('pdf');await new Promise((res,rej)=>{const doc=new PDFDocument({autoFirstPage:false,margin:0});const stream=fs.createWriteStream(out);stream.on('finish',res);stream.on('error',rej);doc.pipe(stream);for(const f of files){const im=doc.openImage(f);const w=im.width,h=im.height;doc.addPage({size:[w,h],margin:0});doc.image(im,0,0,{width:w,height:h})}doc.end()});return out}
async function pdfToImages(input,maxPages=6){const pdfjs=require('pdfjs-dist/legacy/build/pdf.js');const {createCanvas}=require('canvas');const data=new Uint8Array(fs.readFileSync(input));const pdf=await pdfjs.getDocument({data,disableWorker:true}).promise;const outs=[];for(let p=1;p<=Math.min(pdf.numPages,maxPages);p++){const page=await pdf.getPage(p),vp=page.getViewport({scale:1.5}),canvas=createCanvas(vp.width,vp.height),ctx=canvas.getContext('2d');await page.render({canvasContext:ctx,viewport:vp}).promise;const f=tmp('png');fs.writeFileSync(f,canvas.toBuffer('image/png'));outs.push(f)}return{files:outs,totalPages:pdf.numPages}}
function zipFiles(files,names){const out=tmp('zip'),z=new AdmZip();files.forEach((f,i)=>z.addLocalFile(f,'',safeName(names?.[i]||path.basename(f))));z.writeZip(out);return out}
function unzip(input){const d=dir(),z=new AdmZip(input);for(const e of z.getEntries()){const n=path.normalize(e.entryName).replace(/^([/\\])+/, '');if(n.includes('..'+path.sep))throw new Error('Archive ZIP dangereuse.');}z.extractAllTo(d,true);return listFiles(d)}
function seven(input,mode='extract',files=[]){return new Promise((res,rej)=>{let stream,out;if(mode==='extract'){out=dir();stream=Seven.extractFull(input,out,{$bin:sevenBin.path7za,$progress:false})}else{out=tmp('7z');stream=Seven.add(out,files,{$bin:sevenBin.path7za,$progress:false})}stream.on('end',()=>res(mode==='extract'?listFiles(out):out));stream.on('error',rej)})}
async function unrar(input){const buf=fs.readFileSync(input),ex=createExtractorFromData({data:new Uint8Array(buf)}),list=ex.getFileList();if(list[0].state!=='SUCCESS')throw new Error('RAR illisible ou protégé.');const extracted=ex.extract();if(extracted[0].state!=='SUCCESS')throw new Error('Extraction RAR impossible.');const d=dir(),outs=[];for(const f of extracted[1].files){if(f.fileHeader.flags.directory)continue;const n=safeName(f.fileHeader.name),dest=path.join(d,n);fs.writeFileSync(dest,Buffer.from(f.extraction));outs.push(dest)}return outs}
function listFiles(d){const out=[];for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isFile())out.push(p);else if(e.isDirectory())out.push(...listFiles(p))}return out}
function hash(input,algo='sha256'){return crypto.createHash(algo).update(fs.readFileSync(input)).digest('hex')}
function archiveInfo(input){const ext=path.extname(input).toLowerCase();if(ext==='.zip'){const z=new AdmZip(input),entries=z.getEntries();return{type:'ZIP',count:entries.length,names:entries.slice(0,30).map(e=>e.entryName)}}return{type:ext.slice(1).toUpperCase()||'archive',count:null,names:[]}}
function cleanup(...xs){for(const x of xs.flat(Infinity).filter(Boolean)){try{const st=fs.statSync(x);if(st.isDirectory())fs.rmSync(x,{recursive:true,force:true});else fs.unlinkSync(x)}catch(_){}}}
module.exports={getInput,imageConvert,videoConvert,imagesToPdf,pdfToImages,zipFiles,unzip,seven,unrar,hash,archiveInfo,cleanup,tmp,safeName,MAX_BYTES};