'use strict';

function normalize(text=''){return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();}
function hash(text=''){let h=0;for(const c of String(text))h=((h<<5)-h+c.charCodeAt(0))|0;return Math.abs(h);}
function pick(list,seed=''){return list[hash(seed)%list.length];}
function lastUser(messages=[]){for(let i=messages.length-1;i>=0;i--)if(messages[i]?.role==='user')return String(messages[i].content||'').trim();return'';}
function recent(messages=[],role){return messages.filter(m=>m?.role===role).slice(-5).map(m=>String(m.content||'')).filter(Boolean);}
function safeArithmetic(text){const m=String(text).match(/(?:combien\s+(?:font|fait)|calcule|calcul|=)?\s*(-?\d+(?:\.\d+)?)\s*([+\-*/])\s*(-?\d+(?:\.\d+)?)\s*\??$/i);if(!m)return null;const a=Number(m[1]),op=m[2],b=Number(m[3]);if(!Number.isFinite(a)||!Number.isFinite(b))return null;if(op==='/'&&b===0)return'Division par zéro impossible';const value=op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b;return Number.isFinite(value)?`${a} ${op} ${b} = ${value}`:null;}
function stripContextHints(text=''){return String(text).replace(/\n\n\[Contexte implicite:[\s\S]*$/i,'').trim();}
function keywords(v=''){return new Set(normalize(v).replace(/[^a-z0-9]+/g,' ').split(/\s+/).filter(x=>x.length>3&&!/^(avec|pour|dans|mais|comme|quoi|quel|quelle|comment|pourquoi|cette|celui|elles|vous|nous)$/.test(x)));}
function groundedContext(messages=[],query=''){const systems=messages.filter(m=>m?.role==='system').map(m=>String(m.content||'')).join('\n'),q=keywords(query),rows=systems.split('\n').map(x=>x.replace(/^[-•]\s*/,'').trim()).filter(x=>x.length>8&&x.length<600);const scored=[];for(const row of rows){const w=keywords(row);let hit=0;for(const k of q)if(w.has(k))hit++;if(hit)scored.push({row,score:hit/(q.size||1)});}return scored.sort((a,b)=>b.score-a.score).slice(0,4).map(x=>x.row);}
function detectMood(t){if(/\b(triste|mal|deprime|fatigue|angoisse|peur|stresse|seul|seule)\b/.test(t))return'low';if(/\b(content|heureux|super|genial|cool|incroyable)\b/.test(t))return'high';return'neutral';}
function conversationalFallback(messages=[]){const raw=stripContextHints(lastUser(messages)),t=normalize(raw).replace(/^exaucee\s*[,!:;\-]?\s*/i,''),previousAssistant=recent(messages,'assistant').at(-1)||'',seed=raw+previousAssistant;if(!t)return pick([`Je suis là. Vas-y, je t'écoute.`,`Oui ? Dis-moi.`,`Je t'écoute, continue.`],seed);const grounded=groundedContext(messages,raw);if(/\?$|\b(qui|quoi|quel|quelle|comment|pourquoi|rappelle|souviens)\b/.test(t)&&grounded.length){return`D’après le contexte que j’ai réellement sous la main :\n${grounded.map(x=>`• ${x}`).join('\n')}`;}const mood=detectMood(t);if(mood==='low')return pick([`Ça n'a pas l'air simple. Raconte-moi ce qui s'est passé, même en vrac, et on remet ça au clair ensemble.`,`Je vois que ça te pèse. Dis-moi ce qui te dérange le plus là, maintenant — on part de ça.`],seed);if(/^(oui|ok|d'accord|vas[- ]y|continue|encore)\b/.test(t)&&previousAssistant)return`D'accord, je continue à partir de ce qu’on disait. ${previousAssistant.length>600?'Je vais aller à l’essentiel pour la suite.':''}`.trim();if(/\b(tu en penses quoi|ton avis|qu'en penses tu)\b/.test(t))return`Je peux te donner un avis utile à partir des éléments disponibles. Là, le point principal que je vois est : ${grounded[0]||'il me manque encore un fait concret pour trancher proprement'}.`;if(/\b(aide[- ]moi|j'ai besoin d'aide|je fais comment)\b/.test(t))return`Oui. Donne-moi le résultat exact que tu veux obtenir et l’état actuel ; je vais raisonner à partir de ça sans te faire recommencer inutilement.`;if(/\b(cree|execute|modifie|supprime|programme|planifie|organise|corrige)\b/.test(t))return`J’ai compris qu’il s’agit d’une action. Je peux préparer le plan et utiliser les outils locaux quand ils sont disponibles, mais je ne vais pas prétendre avoir exécuté quelque chose que le runtime n’a pas réellement confirmé.`;if(/\?$/.test(raw))return`Je n’ai pas assez de données locales fiables pour affirmer ce fait sans inventer. Si la recherche ou un moteur externe est disponible, je dois m’appuyer dessus ; sinon je peux seulement raisonner à partir du contexte déjà connu.`;return pick([`D'accord, je garde ce fil. Donne-moi la suite ou le résultat précis que tu veux obtenir.`,`Je te suis. On peut transformer ça en plan concret, vérifier un point ou continuer la discussion.`],seed);}
function highConfidence(messages=[]){const raw=stripContextHints(lastUser(messages)),t=normalize(raw).replace(/^exaucee\s*[,!:;\-]?\s*/i,'');if(!t)return null;const arithmetic=safeArithmetic(t);if(arithmetic)return{text:pick([`Ça donne *${arithmetic}*.`,`Résultat : *${arithmetic}*.`],raw),confidence:0.99};if(/^(salut|bonjour|bonsoir|hello|hey|coucou)\b/.test(t))return{text:pick([`Coucou 🌸 Qu'est-ce qu'on fait ?`,`Hey, je suis là. Tu veux parler de quoi ?`,`Salut 🌸 Dis-moi.`],raw),confidence:0.98};if(/\b(qui es[- ]tu|presente[- ]toi|ton nom|comment tu t'appelles)\b/.test(t))return{text:`Je suis Exaucée 🌸, l’assistante intégrée à THE BIG DIPPER. Je peux discuter, garder le contexte, mémoriser des éléments utiles, rechercher, planifier, créer des workflows sûrs et piloter les capacités autorisées du bot.`,confidence:0.99};if(/\b(merci|thanks|thank you)\b/.test(t))return{text:pick([`Avec plaisir.`,`Toujours 🌸`,`Pas de souci.`],raw),confidence:0.99};if(/\b(comment vas[- ]tu|ca va|tu vas bien)\b/.test(t))return{text:pick([`Oui, tranquille 🌸 Et toi ?`,`Ça va bien. Quoi de neuf de ton côté ?`],raw),confidence:0.98};return null;}
class LocalBrain{answer(messages=[]){return highConfidence(messages);}fallback(messages=[]){return{provider:'exaucee-local-brain-v2',text:conversationalFallback(messages)};}}
module.exports={LocalBrain,highConfidence,conversationalFallback,safeArithmetic,stripContextHints,groundedContext};
