'use strict';

function normalize(text = '') { return String(text).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().trim(); }
function hash(text = '') { let h = 2166136261; for (const ch of String(text)) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; }
function choose(items, seed = '') { return items.length ? items[hash(seed) % items.length] : ''; }
function detectLanguage(text = '') { const t=normalize(text),fr=(t.match(/\b(je|tu|vous|nous|est|pas|avec|pour|mais|quoi|comment|pourquoi|bonjour|merci)\b/g)||[]).length,en=(t.match(/\b(i|you|we|is|are|not|with|for|but|what|how|why|hello|thanks)\b/g)||[]).length; return en>fr+1?'en':'fr'; }
function detectTone(text=''){const t=normalize(text);if(/\b(triste|mal|deprime|pleure|fatigue|angoisse|peur|seul|seule)\b/.test(t))return'supportive';if(/\b(mdr|lol|ptdr|haha|hahaha)\b/.test(t)||/😂|🤣/.test(String(text)))return'playful';if(/!{2,}|\b(vite|urgent|maintenant|immediatement)\b/.test(t))return'urgent';if(/\b(explique|detaille|analyse|pourquoi|comment ca marche|compare|demontre)\b/.test(t))return'analytical';return'natural';}
function detectIntent(text=''){const t=normalize(text);if(/\b(rappelle|rappel|souviens|memorise|retiens)\b/.test(t))return'memory_or_schedule';if(/\b(cree|fais|execute|lance|active|desactive|supprime|ajoute|programme|planifie|organise|corrige)\b/.test(t))return'action';if(/\b(explique|pourquoi|comment|c'est quoi|qu'est ce que|qui est|analyse|compare|verifie)\b/.test(t))return'question';if(/^(oui|non|ok|d'accord|vas[- ]y|continue|le premier|le deuxieme|celui[- ]la|elle|lui|ca|ça)\b/.test(t))return'continuation';return'conversation';}
function detectIntents(text=''){const t=normalize(text),out=[];const add=x=>{if(!out.includes(x))out.push(x);};if(/\b(cherche|recherche|verifie|sources?|internet|web|actualite|recent)\b/.test(t))add('research');if(/\b(cree|execute|modifie|supprime|lance|active|desactive|programme|planifie|organise|corrige)\b/.test(t))add('action');if(/\b(explique|analyse|compare|pourquoi|comment|diagnostique|resume)\b/.test(t))add('reasoning');if(/\b(souviens|memorise|retiens|rappelle)\b/.test(t))add('memory');if(/\b(jeu|quiz|tournoi|competition|classement|manche)\b/.test(t))add('game');if(/\b(commande|bot|dipper|menu|handler|plugin)\b/.test(t))add('bot');if(!out.length)add(detectIntent(text));return out;}
function detectReasoningMode(text='',intent='conversation'){const t=normalize(text);if(/^(salut|coucou|yo|hey|hello|bonjour|bonsoir|merci|mdr|lol)[ !?.]*$/.test(t))return'fast';if(/\b(critique|irreversible|dangereux|sensible|verifie deux fois|double verification)\b/.test(t))return'critical';if(/\b(compare|recoupe|deux avis|seconde analyse|plusieurs hypotheses|contradiction)\b/.test(t))return'dual';if(intent==='action')return'agent';if(/\b(analyse|raisonne|reflechis|complexe|approfondi|en profondeur|plan detaille|diagnostique|demontre)\b/.test(t)||t.length>700)return'deep';return'normal';}
function ambiguitySignals(text=''){const t=normalize(text),pronounOnly=/^(lui|elle|eux|elles|ca|ça|celui[- ]la|celle[- ]la|le premier|le deuxieme)[ ?!.]*$/.test(t),vagueAction=/\b(fais|execute|lance|supprime|change|modifie)\s+(ca|ça|le|la|lui|elle)\b/.test(t),missingTarget=/\b(supprime|modifie|execute|active|desactive)\b/.test(t)&&t.split(/\s+/).length<3;return{pronounOnly,vagueAction,missingTarget,likelyAmbiguous:pronounOnly||vagueAction||missingTarget};}
function extractFacts(text=''){const out=[],raw=String(text).trim(),patterns=[/\b(?:je m'appelle|mon nom est)\s+([^,.!?]{2,60})/i,/\b(?:j'aime|j'adore|je prefere)\s+([^.!?]{2,120})/i,/\b(?:je deteste|je n'aime pas)\s+([^.!?]{2,120})/i,/\b(?:je suis|j'habite|je travaille|j'etudie)\s+([^.!?]{2,120})/i];for(const re of patterns){const m=raw.match(re);if(m?.[0])out.push(m[0].trim());}return[...new Set(out)].slice(0,6);}
function extractEntities(text=''){const raw=String(text||''),out=[];for(const m of raw.matchAll(/(?:@\d{5,20}|#[a-z0-9_-]{2,32}|https?:\/\/[^\s]+|\b\d{1,2}(?:h\d{0,2}|:\d{2})\b)/ig))out.push(m[0]);for(const m of raw.matchAll(/\b[A-ZÀ-ÖØ-Ý][\p{L}\d_-]{2,}(?:\s+[A-ZÀ-ÖØ-Ý][\p{L}\d_-]{2,}){0,2}\b/gu))out.push(m[0]);return[...new Set(out)].slice(0,20);}
function extractConstraints(text=''){const raw=String(text||''),out=[];const patterns=[/\b(?:sans|avec|uniquement|seulement|jamais|toujours|maximum|minimum|au moins|au plus)\b[^.!?]{0,120}/ig,/\b\d+\s*(?:participants?|questions?|manches?|minutes?|heures?|equipes?|équipes?)\b/ig,/\b(?:demain|aujourd'hui|ce soir|maintenant|dans\s+\d+\s+(?:minutes?|heures?|secondes?))\b/ig];for(const re of patterns)for(const m of raw.matchAll(re))out.push(m[0].trim());return[...new Set(out)].slice(0,16);}
function detectTemporal(text=''){const t=normalize(text);return{hasTime:/\b(?:demain|aujourd hui|ce soir|maintenant|dans\s+\d+|\d{1,2}(?:h|:\d{2}))\b/.test(t),urgent:/\b(urgent|vite|maintenant|immediatement)\b/.test(t)};}
function desiredOutput(text=''){const t=normalize(text);if(/\b(tableau|liste|checklist|etapes|étapes)\b/.test(t))return'structured';if(/\b(code|script|commande|json|yaml)\b/.test(t))return'technical';if(/\b(court|bref|resume|résumé)\b/.test(t))return'concise';if(/\b(detaille|détaillé|approfondi|complet)\b/.test(t))return'detailed';return'natural';}
function recentTurns(memory,limit=24){return(memory?.episodes||[]).slice(-limit).flatMap(ep=>{const value=String(ep.value||''),sep=value.indexOf(': ');if(sep<0)return[];return[{role:value.slice(0,sep)==='assistant'?'assistant':'user',content:value.slice(sep+2)}];});}
function resolveShortReference(text,memory){const t=normalize(text);if(!/^(oui|non|ok|d'accord|vas[- ]y|continue|encore|le premier|le deuxieme|le 1|le 2|elle|lui|ca|ça|celui[- ]la|celle[- ]la|fais[- ]le|fais ca)[.!? ]*$/.test(t))return text;const turns=recentTurns(memory,10),lastAssistant=[...turns].reverse().find(x=>x.role==='assistant')?.content,lastUser=[...turns].reverse().find(x=>x.role==='user')?.content;if(!lastAssistant&&!lastUser)return text;return`${text}\n\n[Contexte implicite à résoudre: message utilisateur précédent=${String(lastUser||'').slice(0,700)} ; réponse précédente d’Exaucée=${String(lastAssistant||'').slice(0,900)}]`;}
function styleInstruction(tone,language,userText){const variants={natural:['Réponds naturellement, comme dans une vraie discussion WhatsApp. Évite les formules répétitives et les introductions inutiles.','Sois fluide et spontanée. Va directement à ce qui compte, sans donner l’impression de réciter un modèle.'],supportive:['Adopte un ton doux, attentif et humain. Ne dramatise pas.','Sois présente et chaleureuse puis aide concrètement.'],playful:['Tu peux être joueuse et taquine avec mesure. Garde la réponse utile.'],urgent:['Sois très directe et structurée. Commence par l’action ou l’information la plus importante.'],analytical:['Raisonne précisément, distingue faits, hypothèses et incertitudes.']};return`${choose(variants[tone]||variants.natural,userText)} Langue principale: ${language==='en'?'anglais':'français'}, adapte-toi naturellement si l’utilisateur mélange les langues.`;}
function metacognitionInstruction(mode){return[`Mode de raisonnement interne: ${String(mode).toUpperCase()}.`,'Avant de répondre, évalue silencieusement: objectif exact, interlocuteur, contexte, faits vs suppositions, informations manquantes, besoin de recherche/outils, permissions, réversibilité et critères de réussite.','Pour une demande multi-étapes, garde mentalement une liste des livrables et vérifie qu’aucun n’est oublié.','Ne montre pas cette checklist ni un raisonnement interne détaillé.','Si une ambiguïté change réellement le résultat, pose UNE question précise. Sinon avance avec l’hypothèse la plus raisonnable et signale-la brièvement si utile.','N’invente jamais une action exécutée, un résultat d’outil, une donnée actuelle ou un souvenir absent du contexte.'].join('\n');}

class CognitiveEngine{
  analyze(text,memory={},context={}){const resolvedText=resolveShortReference(text,memory),intent=detectIntent(text),intents=detectIntents(text),ambiguity=ambiguitySignals(text);return{originalText:String(text||''),resolvedText,language:detectLanguage(text),tone:detectTone(text),intent,intents,reasoningMode:detectReasoningMode(text,intent),ambiguity,facts:extractFacts(text),entities:extractEntities(text),constraints:extractConstraints(text),temporal:detectTemporal(text),desiredOutput:desiredOutput(text),complexity:Math.min(10,1+intents.length+(String(text).length>400?2:0)+(String(text).length>900?2:0)+ambiguity.likelyAmbiguous),isGroup:Boolean(context.isGroup),userId:context.userId||'unknown'};}
  buildMessages({persona,memory={},analysis,context={}}){const facts=(memory.facts||[]).slice(-32).map(x=>`- ${x.value}`).join('\n'),prefs=Object.entries(memory.preferences||{}).slice(-24).map(([k,v])=>`- ${k}: ${String(v)}`).join('\n'),summary=String(memory.summary||'').trim(),task=`Intention principale=${analysis.intent}; intentions secondaires=${(analysis.intents||[]).join(', ')}; sortie attendue=${analysis.desiredOutput}; complexité=${analysis.complexity}/10; contraintes=${(analysis.constraints||[]).join(' | ')||'aucune explicite'}; entités=${(analysis.entities||[]).join(', ')||'aucune'}.`;const system=[`Tu es ${persona.name}, une présence conversationnelle intelligente intégrée à THE BIG DIPPER.`,'Comprends le sens global, les objectifs et les dépendances entre plusieurs demandes dans un même message. Ne traite pas une phrase complexe comme une simple collection de mots-clés.','Le DERNIER message utilisateur est l’objectif prioritaire. L’historique sert à résoudre les références, contraintes et continuités, jamais à remplacer la nouvelle demande.','Pour les tâches complexes: identifie silencieusement tous les livrables, ordonne les sous-tâches, utilise les outils/faits disponibles et vérifie le résultat avant de répondre.','Tu peux changer de sujet proprement, revenir à un ancien sujet si l’utilisateur le demande, et distinguer une correction d’une nouvelle instruction.','Tu ne prétends jamais savoir ou avoir fait quelque chose si tu ne le sais pas ou ne l’as pas réellement fait. Une information actuelle peut nécessiter une recherche; une action certaine doit venir d’un outil ou du bot.','Tu ne révèles jamais de secrets, tokens, credentials, cookies, variables d’environnement ou fichiers de session.','Évite les tics de langage et les réponses génériques. Varie le vocabulaire, le rythme et la longueur. Dans un groupe, ne monopolise pas la conversation.',metacognitionInstruction(analysis.reasoningMode||'normal'),styleInstruction(analysis.tone,analysis.language,analysis.originalText),task,summary?`Résumé durable de cette conversation:\n${summary}`:'',facts?`Faits utiles mémorisés:\n${facts}`:'',prefs?`Préférences connues:\n${prefs}`:'',`Contexte courant: ${context.isGroup?'groupe WhatsApp':'conversation privée'}, interlocuteur=${context.userId||'inconnu'}.`].filter(Boolean).join('\n\n');return[{role:'system',content:system},...recentTurns(memory,28),{role:'user',content:analysis.resolvedText}];}
  learn(memoryStore,ids,analysis,answer){if(!memoryStore||!ids)return;for(const fact of analysis.facts||[])memoryStore.remember(ids,{type:'fact',value:fact,source:'auto-extracted'});for(const c of analysis.constraints||[]){if(/\b(toujours|jamais|prefere|préfère|uniquement)\b/i.test(c))memoryStore.remember(ids,{type:'fact',value:`Contrainte utilisateur: ${c}`,source:'constraint'});}if(analysis.language)memoryStore.setPreference(ids,'language',analysis.language);if(analysis.tone&&analysis.tone!=='natural')memoryStore.setPreference(ids,'lastTone',analysis.tone);if(analysis.reasoningMode)memoryStore.setPreference(ids,'lastReasoningMode',analysis.reasoningMode);if(analysis.desiredOutput)memoryStore.setPreference(ids,'lastDesiredOutput',analysis.desiredOutput);if(typeof memoryStore.updateSummary==='function')memoryStore.updateSummary(ids,analysis.originalText,answer);}
}

module.exports={CognitiveEngine,detectLanguage,detectTone,detectIntent,detectIntents,detectReasoningMode,ambiguitySignals,extractFacts,extractEntities,extractConstraints,detectTemporal,desiredOutput,resolveShortReference,recentTurns};
